#!/usr/bin/env python3
"""Build v2.1.1 public-only option observations for the scored research universe.

Symbols are generated by v211_serenity_top20.py from the owner-independent
scored universe.  One provider failure is represented as a public status record
instead of aborting the entire twice-daily refresh.
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import build_line_public_options as base

DEFAULT_SYMBOLS_PATH = ROOT / "data" / "cache" / "line_public_symbols_generated.json"
DEFAULT_OUTPUT_PATH = ROOT / "data" / "cache" / "options_public_latest.json"

LOGGER = logging.getLogger("v211-public-options")
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")


def failure_record(item: dict[str, Any], status: str) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "ticker": item["ticker"],
        "provider_symbol": item["market_data_ticker"],
        "currency": item["currency"],
        "current_price": None,
        "retrieved_at": datetime.now(timezone.utc).isoformat(),
        "status": status,
        "quote_source": "yfinance",
        "quote_delay_status": "THIRD_PARTY_DELAY_UNKNOWN",
        "provider_scope": "public_only",
        "line_public_eligible": True,
        "ibkr_connected": False,
        "brokerage_data_included": False,
        "account_data_included": False,
        "position_data_included": False,
        "owner_watchlist_inherited": False,
        "periods": {},
    }


def build(
    *,
    symbols_path: Path = DEFAULT_SYMBOLS_PATH,
    market_path: Path = base.DEFAULT_MARKET_PATH,
    policy_path: Path = base.DEFAULT_POLICY_PATH,
    output_path: Path = DEFAULT_OUTPUT_PATH,
    sleep_seconds: float = 0.25,
) -> list[dict[str, Any]]:
    symbols = base.load_public_symbols(symbols_path)
    if not symbols:
        raise ValueError("Generated v2.1.1 public symbol universe is empty")
    prices = base.load_market_prices(market_path)
    policy = base.load_policy(policy_path)

    results: list[dict[str, Any]] = []
    for index, item in enumerate(symbols, start=1):
        ticker = item["ticker"]
        provider_symbol = item["market_data_ticker"]
        price = prices.get(ticker)
        if not price:
            try:
                price = base.safe_float(base.yf.Ticker(provider_symbol).fast_info.last_price)
            except Exception as exc:
                LOGGER.warning("Underlying quote failed for %s: %s", ticker, type(exc).__name__)
        if not price or price <= 0:
            results.append(failure_record(item, "NO_UNDERLYING_PRICE"))
            continue

        LOGGER.info("[%d/%d] v2.1.1 public option snapshot for %s", index, len(symbols), ticker)
        try:
            raw = base.get_option_suggestion(
                ticker,
                price,
                policy=policy,
                position=None,
                yf_ticker=provider_symbol,
            )
            record = base.to_public_record(raw, item["currency"])
            record["current_price"] = record.get("current_price") or price
            results.append(record)
        except Exception as exc:
            LOGGER.warning("Public option observation failed for %s: %s", ticker, type(exc).__name__)
            failed = failure_record(item, "PROVIDER_ERROR")
            failed["current_price"] = price
            results.append(failed)
        if sleep_seconds > 0:
            time.sleep(sleep_seconds)

    if len(results) != len(symbols):
        raise ValueError("v2.1.1 public option record count does not match the generated symbol universe")
    base.atomic_write_json(output_path, results)
    return results


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--symbols", type=Path, default=DEFAULT_SYMBOLS_PATH)
    parser.add_argument("--market", type=Path, default=base.DEFAULT_MARKET_PATH)
    parser.add_argument("--policy", type=Path, default=base.DEFAULT_POLICY_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    parser.add_argument("--sleep", type=float, default=0.25)
    args = parser.parse_args()
    try:
        records = build(
            symbols_path=args.symbols,
            market_path=args.market,
            policy_path=args.policy,
            output_path=args.output,
            sleep_seconds=max(0.0, args.sleep),
        )
    except (FileNotFoundError, json.JSONDecodeError, ValueError) as exc:
        LOGGER.error("v2.1.1 public option build failed: %s", exc)
        return 1
    print(json.dumps({
        "status": "PASS",
        "records": len(records),
        "output": str(args.output),
        "provider_scope": "public_only",
        "ibkr_connected": False,
        "owner_watchlist_inherited": False,
    }, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
