import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { assertLineMessages } from "../src/line-messages";
import { parseQuery } from "../src/core";
import { v213PublicLineAnswer } from "../src/v213/rich-menu";
import { SNAPSHOT_SEAL_KEY } from "../src/v213/snapshot-seal";
import { asKv, MemoryKv } from "./fake-kv";
import { sealUnboundReport } from "./sealed-report-migration";

// The bodies below are the EXACT strings the real Python producer main + sealer emitted (tests/fixtures/options_nonus_publisher_cases.py,
// regenerated byte for byte by tests/test_options_nonus_bridge.py). They are sealed verbatim, never re-encoded.
const bridge = JSON.parse(readFileSync(resolve(__dirname, "fixtures/options-nonus-publisher.json"), "utf-8"));
const RUN = "20260930T170000Z-abcdefabcde9";
const FIXED_NOW = Date.parse(bridge.clock);
const stamp = "2026-09-30T16:59:00Z";
const FEEDS = [{ id: "nordic-shares", url: "https://example.com", retrieved_at: stamp, sha256: "a".repeat(64), rows: 1 },
               { id: "lse-aim", url: "https://api.londonstockexchange.com/api/v1/components/refresh", retrieved_at: stamp, sha256: "d".repeat(64), rows: 1 }];

type Options = { options?: string; quotes?: string; tamper?: boolean; dropBlob?: boolean; badPointer?: boolean; flex?: boolean };
type Cycle = { unavailable?: string; ticker?: string; currency?: string; dte?: number; multiplier?: number; suggestions?: { strike: number }[] };

async function sha(text: string): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, "0")).join("");
}

function caseBodies(caseId: string): { options: string; quotes: string } {
  const entry = bridge.cases[caseId];
  if (!entry) throw new Error(`missing bridge case ${caseId}`);
  return entry.kind === "REJECTED" ? entry.retained_old_bodies : entry.bodies;
}

function optionsOf(caseId: string): Record<string, Record<string, Cycle>> {
  return JSON.parse(caseBodies(caseId).options).options;
}

async function sealedEnv(caseId: string, extra: Options = {}) {
  const bodies = caseBodies(caseId);
  const kv = new MemoryKv();
  kv.values.set("v213:top20-report:latest", JSON.stringify({ synthetic: "report" }));
  kv.values.set("last_successful_pipeline_timestamp", new Date(FIXED_NOW - 60_000).toISOString().replace(/\.\d{3}Z$/, "Z"));
  await sealUnboundReport(kv, RUN);
  const shard = (bucket: string, rows: unknown[]) => ({ schema: "v213-identity-shard-v2", kind: "symbol", bucket, generated_at: stamp, feeds: FEEDS, rows });
  const lazy: Record<string, string> = {
    "v213:identity:v2:sym:S": JSON.stringify(shard("S", [["SIVE", "Nasdaq Stockholm", "SWEDEN", "Sweden", "Sivers Semiconductors", null, "COMMON_STOCK", "SEK", 0]])),
    "v213:identity:v2:sym:V": JSON.stringify(shard("V", [["VOLV B", "Nasdaq Stockholm", "SWEDEN", "Sweden", "Volvo, AB ser. B", null, "COMMON_STOCK", "SEK", 0]])),
    "v213:identity:v2:sym:N": JSON.stringify(shard("N", [["NVDA", "NASDAQ", "US", "United States", "NVIDIA Corporation", null, "COMMON_STOCK", "USD", 0]])),
    "v213:identity:v2:sym:I": JSON.stringify(shard("I", [["IQE", "LSE AIM", "UK", "United Kingdom", "IQE PLC", null, "COMMON_STOCK", "GBX", 1]])),
    "v213:options:v2": extra.options ?? bodies.options,
    "v213:quotes:v1": extra.quotes ?? bodies.quotes,
  };
  const sealKey = `snapshot:${RUN}:${SNAPSHOT_SEAL_KEY}`;
  const seal = JSON.parse(kv.values.get(sealKey)!);
  for (const [key, body] of Object.entries(lazy)) {
    const digest = await sha(body);
    seal.objects[key] = { sha256: digest, utf8_bytes: new TextEncoder().encode(body).byteLength };
    kv.values.set(`blob:v1:${digest}`, extra.tamper && key === "v213:options:v2" ? body + " " : body);
    if (extra.dropBlob && key === "v213:options:v2") kv.values.delete(`blob:v1:${digest}`);
  }
  const sealText = JSON.stringify(seal);
  kv.values.set(sealKey, sealText);
  const pointer = JSON.parse(kv.values.get("snapshot:current")!);
  pointer.seal_sha256 = extra.badPointer ? "0".repeat(64) : await sha(sealText);
  kv.values.set("snapshot:current", JSON.stringify(pointer));
  return {
    PUBLIC_CACHE: asKv(kv), TENANT_PRIVATE_CACHE: asKv(new MemoryKv()), EPHEMERAL_SECURITY_CACHE: asKv(new MemoryKv()),
    V21_TOP20_MAX_AGE_SECONDS: "7200", V213_LINE_PRESENTATION: extra.flex ? "flex" : "text",
  };
}

async function reply(env: unknown, command: string): Promise<any[]> {
  const messages = await v213PublicLineAnswer(env as never, parseQuery(command)) as any[];
  expect(messages, command).toBeDefined();
  assertLineMessages(messages);
  return messages;
}

const textOf = (messages: any[]) => messages.map(m => m.text ?? JSON.stringify(m.contents ?? m)).join("\n");
const strikeOf = (cycle: Cycle) => cycle.suggestions![0]!.strike.toFixed(2);

beforeEach(() => { vi.useFakeTimers(); vi.setSystemTime(FIXED_NOW); });
afterEach(() => { vi.useRealTimers(); });

describe("OPTIONS-NONUS-02 bridge: exact Python-emitted bodies through the Worker", () => {
  it("consumes the exact producer strings: the sealed digest equals the fixture's hash", async () => {
    for (const [caseId, entry] of Object.entries<any>(bridge.cases)) {
      const bodies = caseBodies(caseId);
      const hashes = entry.kind === "REJECTED" ? entry.retained_old_hashes : entry.hashes;
      expect(await sha(bodies.options), caseId).toBe(hashes.options_sha256);
      expect(await sha(bodies.quotes), caseId).toBe(hashes.quotes_sha256);
    }
  });

  it("answers Sive / SIVE / SIVE.ST with listed-but-out-of-policy date context in TEXT and Flex", async () => {
    const env = await sealedEnv("retained_sive_sept30");
    for (const command of ["Sive 每月期權", "SIVE 每月期權", "SIVE.ST 每月期權"]) {
      const text = textOf(await reply(env, command));
      expect(text).toContain("SIVE.ST 每月期權");
      expect(text).toContain("本次回應有上市買權；所列到期不在21–45天策略範圍");
      expect(text).toContain("2026-10-16（16天）");
      expect(text).toContain("2026-11-20（51天）");
      expect(text).toContain("已封存之公開觀察");
      expect(text).not.toContain("年化權利金");
      expect(text).not.toMatch(/\d+\.\d\d SEK/);
    }
    for (const command of ["Sive 每週期權", "SIVE.ST 每週期權"]) {
      const text = textOf(await reply(env, command));
      expect(text).toContain("SIVE.ST 每週期權");
      expect(text).toContain("所列到期不在3–14天策略範圍");
    }
    const flexEnv = await sealedEnv("retained_sive_sept30", { flex: true });
    const flex = await reply(flexEnv, "SIVE.ST 每月期權");
    expect(flex[0].type).toBe("flex");
    const flexText = JSON.stringify(flex[0].contents) + flex[0].altText;
    expect(flexText).toContain("SIVE.ST");
    expect(flexText).toContain("所列到期不在21–45天策略範圍");
  });

  it("shows genuine native and US strategies with their own identity, currency, strike and 100 multiplier", async () => {
    const options = optionsOf("retained_sive_sept30");
    const env = await sealedEnv("retained_sive_sept30");
    const rows: [string, string, string][] = [["VOLV B 每月期權", "VOLV-B.ST", "SEK"], ["VOLV-B.ST 每月期權", "VOLV-B.ST", "SEK"],
                                              ["AZN.ST 每月期權", "AZN.ST", "SEK"], ["AZN 每月期權", "AZN", "USD"]];
    for (const [command, key, currency] of rows) {
      const cycle = options[key]!.monthly!;
      expect(cycle.ticker).toBe(key);
      expect(cycle.multiplier).toBe(100);
      const text = textOf(await reply(env, command));
      expect(text).toContain(key);
      expect(text).toContain(currency === "SEK" ? `${strikeOf(cycle)} SEK` : `$${strikeOf(cycle)}`);
    }
    const flex = await reply(await sealedEnv("retained_sive_sept30", { flex: true }), "VOLV-B.ST 每月期權");
    expect(flex[0].type).toBe("flex");
    expect(JSON.stringify(flex[0].contents)).toContain(`${strikeOf(options["VOLV-B.ST"]!.monthly!)} SEK`);
    // explicit .ST never crosses markets; bare AZN keeps preferring the US listing; a bare Stockholm-only name resolves to its .ST key
    expect(textOf(await reply(env, "SYNTHUS00.ST 每月期權"))).toContain("本輪封存快照未包含 SYNTHUS00.ST");
    expect(textOf(await reply(env, "AZN 每月期權"))).toContain("USD");
    expect(textOf(await reply(env, "AZN.ST 每月期權"))).not.toContain("USD");
  });

  it("carries every producer diagnostic verbatim and never a price for an unavailable record", async () => {
    let unavailableSeen = 0;
    for (const caseId of ["currency_evidence_matrix", "identity_matrix", "terms_and_quote_states", "dte_nordic_matrix", "native_symbol_identity_matrix"]) {
      const env = await sealedEnv(caseId);
      for (const [key, cycles] of Object.entries(optionsOf(caseId))) {
        if (!key.endsWith(".ST")) continue;
        const monthly = cycles.monthly!;
        const text = textOf(await reply(env, `${key} 每月期權`));
        expect(text, `${caseId} ${key}`).toContain(key);
        if (monthly.unavailable) {
          unavailableSeen += 1;
          expect(text, `${caseId} ${key}`).toContain(monthly.unavailable);
          expect(text, `${caseId} ${key}`).not.toMatch(/\d+\.\d\d SEK/);
          expect(text, `${caseId} ${key}`).not.toContain("限價");
        } else {
          expect(monthly.currency).toBe("SEK");
          expect(text, `${caseId} ${key}`).toContain(`${strikeOf(monthly)} SEK`);
        }
      }
    }
    expect(unavailableSeen).toBeGreaterThan(40);
  });

  it("never shows a strategy for a same-root different native contract, and shows the proven decimal/weekly source forms", async () => {
    const env = await sealedEnv("native_symbol_identity_matrix");
    const options = optionsOf("native_symbol_identity_matrix");
    const control = options["SYMCTL.ST"]!.weekly!;
    expect(control.suggestions![0]!.strike).toBe(15.5);
    const controlText = textOf(await reply(env, "SYMCTL.ST 每週期權"));
    expect(controlText).toContain("15.50 SEK");
    expect(textOf(await reply(env, "SYMMON.ST 每月期權"))).toContain(`${strikeOf(options["SYMMON.ST"]!.monthly!)} SEK`);
    expect(textOf(await reply(env, "SYMWEEK.ST 每週期權"))).toContain(`${strikeOf(options["SYMWEEK.ST"]!.weekly!)} SEK`);
    for (const root of ["SYMSTRIKE", "SYMMONTH", "SYMYEAR", "SYMPUT", "SYMPREFIX", "SYMDAY", "SYMUNSUP", "SYMEMPTY", "SYMTYPE", "SYMNONE", "SYMTAGZ", "SYMTAGA", "SYMTAGW", "SYMPREC"]) {
      for (const command of [`${root}.ST 每週期權`, `${root}.ST 每月期權`]) {
        const text = textOf(await reply(env, command));
        expect(text, command).toContain("買權資料無法解析；不推斷是否上市");
        expect(text, command).not.toMatch(/\d+\.\d\d SEK/);
      }
    }
  });

  it("never displays a sub-cent strike as another strike: truthful bounded reason in TEXT and Flex, trailing-zero and cent controls intact", async () => {
    const options = optionsOf("strike_precision_matrix");
    for (const presentation of [false, true]) {
      const env = await sealedEnv("strike_precision_matrix", { flex: presentation });
      for (const key of ["SUBCENT.ST", "YSUBCENT"]) {
        const text = textOf(await reply(env, key + " 每週期權"));
        expect(text, key).toContain("兩位以上小數");
        expect(text, key).not.toMatch(/15\.5[01]\b/);
        expect(text, key).not.toContain("15.505");
        expect(text, key).not.toContain("建議賣出限價");
      }
      expect(textOf(await reply(env, "TRAIL.ST 每週期權")), "flex=" + presentation).toContain("15.50 SEK");
      const mixed = textOf(await reply(env, "MIXED.ST 每週期權"));
      expect(mixed).toContain(strikeOf(options["MIXED.ST"]!.weekly!) + " SEK");
      expect(mixed).not.toContain("15.51");
      expect(mixed).not.toMatch(/15\.50 SEK/);
      expect(textOf(await reply(env, "SUBZERO.ST 每週期權"))).toContain("所選到期無有效雙邊報價");
    }
  });

  it("shows the real weekly VOLVB source shape as a listed out-of-window contract and Yahoo read chains without a usable quote truthfully", async () => {
    const sive = await sealedEnv("retained_sive_sept30");
    const weekly = textOf(await reply(sive, "VOLV-B.ST 每週期權"));
    expect(weekly).toContain("所列到期不在3–14天策略範圍");
    expect(weekly).toContain("2026-10-02（2天）");
    expect(weekly).not.toContain("無法解析");
    const us = await sealedEnv("dte_us_matrix");
    for (const command of ["UYZERO 每週期權", "UYZERO 每月期權", "UYONESIDED 每月期權"]) {
      const text = textOf(await reply(us, command));
      expect(text, command).toContain("所選到期無有效雙邊報價");
      expect(text, command).not.toContain("年化權利金");
    }
  });

  it("distinguishes no-listing evidence from no two-sided quote from strategy miss in the reader output", async () => {
    const env = await sealedEnv("terms_and_quote_states");
    const read = async (key: string) => textOf(await reply(env, `${key} 每月期權`));
    expect(await read("QLASTSALE.ST")).toContain("所選到期無有效雙邊報價");
    expect(await read("QLASTSALE.ST")).not.toContain("沒有年化權利金");
    expect(await read("QMISS.ST")).toContain("沒有年化權利金達 6% 且有雙邊報價的履約價");
    expect(await read("QMISS.ST")).not.toContain("所選到期無有效雙邊報價");
    expect(await read("TSIZE50.ST")).toContain("合約單位非標準100股");
    const identity = await sealedEnv("identity_matrix");
    expect(textOf(await reply(identity, "IDPUT.ST 每月期權"))).toContain("是否上市未確認");
    expect(textOf(await reply(identity, "IDMALONLY.ST 每月期權"))).toContain("不推斷是否上市");
    expect(textOf(await reply(identity, "IDEXC.ST 每月期權"))).toContain("讀取或解析失敗");
  });

  it("keeps integrity, freshness, unsealed and malformed-document refusals on the exact bodies", async () => {
    const bodies = caseBodies("retained_sive_sept30");
    expect(textOf(await reply(await sealedEnv("retained_sive_sept30", { tamper: true }), "VOLV B 每月期權"))).toContain("無法驗證或讀取");
    expect(textOf(await reply(await sealedEnv("retained_sive_sept30", { dropBlob: true }), "VOLV B 每月期權"))).toContain("無法驗證或讀取");
    expect(textOf(await reply(await sealedEnv("retained_sive_sept30", { options: "not json" }), "VOLV B 每月期權"))).toContain("無法驗證或讀取");
    const reshaped = JSON.parse(bodies.options);
    reshaped.options = [];
    expect(textOf(await reply(await sealedEnv("retained_sive_sept30", { options: JSON.stringify(reshaped) }), "VOLV B 每月期權"))).toContain("無法驗證或讀取");
    const invalidCycle = JSON.parse(bodies.options);
    invalidCycle.options["VOLV-B.ST"].monthly.currency = "USD";
    const invalidText = textOf(await reply(await sealedEnv("retained_sive_sept30", { options: JSON.stringify(invalidCycle) }), "VOLV-B.ST 每月期權"));
    expect(invalidText).not.toMatch(/\d+\.\d\d USD/);
    expect(textOf(await reply(await sealedEnv("retained_sive_sept30", { badPointer: true }), "VOLV B 每月期權"))).toContain("OPTION_DATA_UNAVAILABLE");
    vi.setSystemTime(FIXED_NOW + 3 * 3600_000);
    expect(textOf(await reply(await sealedEnv("retained_sive_sept30"), "VOLV-B.ST 每月期權"))).toContain("SEK");
    vi.setSystemTime(FIXED_NOW + 7 * 3600_000);
    expect(textOf(await reply(await sealedEnv("retained_sive_sept30"), "VOLV-B.ST 每月期權"))).toContain("期權快照已逾時");
    vi.setSystemTime(FIXED_NOW);
    expect(textOf(await reply(await sealedEnv("retained_sive_sept30"), "IQE 每月期權"))).toContain("尚未採用此市場");
  });

  it("serves a depleted candidate's RETAINED old file at its original age and never the rejected candidate", async () => {
    for (const caseId of ["depleted_us_1_of_11", "depleted_stockholm_1_of_11"]) {
      const entry = bridge.cases[caseId];
      expect(entry.kind).toBe("REJECTED");
      const old = JSON.parse(entry.retained_old_bodies.options);
      expect(old.generated_at).toBe("2026-09-30T13:00:00Z");
      const env = await sealedEnv(caseId);
      const fresh = textOf(await reply(env, "VOLV-B.ST 每月期權"));
      expect(fresh).toContain("SEK");
      expect(textOf(await reply(env, "DEPUS03 每月期權"))).toContain("本輪封存快照未包含 DEPUS03");
      expect(textOf(await reply(env, "DEPST03.ST 每月期權"))).toContain("本輪封存快照未包含 DEPST03.ST");
      vi.setSystemTime(FIXED_NOW + 3 * 3600_000);
      const stale = textOf(await reply(await sealedEnv(caseId), "VOLV-B.ST 每月期權"));
      expect(stale).toContain("期權快照已逾時");
      expect(stale).toContain("2026-09-30T13:00:00Z");
      expect(stale).not.toMatch(/\d+\.\d\d SEK/);
      vi.setSystemTime(FIXED_NOW);
    }
  });

  it("states only what the snapshot proves when a resolved listing has no option key (no speculative 'may have no options')", async () => {
    const env = await sealedEnv("dte_us_matrix");
    const text = textOf(await reply(env, "SIVE 每月期權"));
    expect(text).toContain("SIVE.ST（Nasdaq Stockholm）：本輪封存資料沒有此掛牌的期權觀察。");
    expect(text).not.toContain("可能沒有掛牌期權");
    expect(text).not.toContain("不在觀察範圍");
  });

  it("publishes boundary-admitted candidates (1/10) with their unavailable diagnostics intact", async () => {
    for (const [caseId, key] of [["us_1_of_10_admitted", "DEPUS03"], ["stockholm_1_of_10_admitted", "DEPST03.ST"]] as const) {
      expect(bridge.cases[caseId].kind).toBe("ADMITTED");
      const cycle = optionsOf(caseId)[key]!.monthly!;
      expect(cycle.unavailable).toBeDefined();
      const text = textOf(await reply(await sealedEnv(caseId), `${key} 每月期權`));
      expect(text).toContain(cycle.unavailable!);
    }
  });
});
